services:
  hansen-gfc-base:
    platform: linux/amd64
    build: .
    image: gcr.io/ee-ramiqcom/hansen-global-forest-change:latest
  hansen-gfc-frontend:
    image: gcr.io/ee-ramiqcom/hansen-global-forest-change:latest
    container_name: hansen-gfc-frontend
    ports:
      - 3000:3000
    networks:
      - mynetwork
    env_file:
      - frontend/.env
    environment:
      - COG_SERVER=http://hansen-gfc-backend:8000
    cpu_count: 1
    mem_limit: 2g
    command: ["npm", "run", "start", '--prefix', "frontend", "--", "--port", "3000"]
  hansen-gfc-backend:
    image: gcr.io/ee-ramiqcom/hansen-global-forest-change:latest
    container_name: hansen-gfc-backend
    ports:
      - 8000:8000
    networks:
      - mynetwork
    env_file:
      - backend/.env
    cpu_count: 8
    mem_limit: 32g
    command: ["npm", "start", '--prefix', "backend", "--", "--port", "8000"]

networks:
  mynetwork:
